FROM microsoft/dotnet:2.1.4-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1.401-sdk AS build
WORKDIR /src
COPY . .

RUN dotnet restore Website/Website.csproj

WORKDIR /src/Website

RUN dotnet build Website.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Website.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .

ENTRYPOINT ["dotnet", "Website.dll"]
